[package]
name = "shiny-png"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
png = "0.18.0"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true
